name: Publish Extension

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        
    - name: Install dependencies
      run: |
        npm install
        npm install -g vsce

    - name: Package
      run: vsce package
      
    - name: Publish
      run: vsce publish -p ${{ secrets.VS_MARKETPLACE_PAT }}
